### ISSUE TITLE
Secure Login icon is empty

### ISSUE THREAD

**Issue by jxerome** [sarahavilov/secure-login#1]
In toolbar, the Secure Login button has no icon displayed. Its is visible only as an empty space. The button works but its invisible display make it harder to find.

I have the problem on Windows 8.1 with a 3840 x 2160 display and Firefox 38 or 39. The icon works perfectly on mac.

**Comment by sarahavilov** [comment]
I just checked the extension on a Windows machine and it worked fine. Can you try it on a clean profile?

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by jxerome** [comment]
Thank you for the answer. I tried with a fresh new profile (using firefox -p to create an other one) and installed only Secure login extension. I still have an empty icon.

Are there any logs or trace that coud help you ?

**Comment by jxerome** [comment]
Here is a screenshot of the toolbar. The grey rectangle is visible only when the mouve is over the button.
![secure-login-no-icon](https://cloud.githubusercontent.com/assets/1355634/8566260/3bace46a-255d-11e5-885a-a6dd3e3adcc0.png)

**Comment by sarahavilov** [comment]
Please close all your Firefox windows. Now open a single one, then open error console (Ctrl + Shift + J). There must be an error there related to the icon not being shown, most likely in the CSS category.

**Comment by jxerome** [comment]
I get only few JS warnings that seem to come from main application or default theme

![console](https://cloud.githubusercontent.com/assets/1355634/8568795/76680544-2571-11e5-9669-6c4238e09fab.png)

(The lines in french means "Event 'key' is not available for some keymaps")

**Comment by sarahavilov** [comment]
Right, there is noting related to the extension here. This time please start Firefox from Command Line with `firefox.exe -jsconsole` argument. I am guessing the log shown by the Error Console misses the initialization warnings.

https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#-jsconsole

**Comment by jxerome** [comment]
I get exacly the same items.It seams that -jsconsole just open the browser console. I tried also with -console. It opens a DOS console. Nothing was logged in this one.

**Comment by sarahavilov** [comment]
How about this one?
https://www.dropbox.com/s/kh668fxo3jfhfd6/sl.xpi?dl=0

Download the XPI file and drop it in a clean profile

**Comment by Betsy25** [comment]
To add to this bug, there is no more toolbar icon available in Firefox nightly v42.

**Comment by sarahavilov** [comment]
@Betsy25 so the toolbar button is gone or empty?

**Comment by Betsy25** [comment]
> @Betsy25 so the toolbar button is gone or empty?

I suspect it is gone, since I got a couple of "empty" items under the customize menu, but I cannot drag&drop them.

**Comment by sarahavilov** [comment]
it works fine for me on Nightly 42. Please close all your Firefox windows. Now open a single window and then open the error console (ctrl + shift + J). Is there anything related to SL there?

**Comment by Betsy25** [comment]
@sarahavilov I dunno if it's related, but I get these : 
``
[CustomizableUI] Custom widget with id loop-button does not return a valid node    -    CustomizableUI.jsm:166
String.prototype.contains() is deprecated and will be removed in a future release; use String.prototype.includes() instead  -  chrome://browser/content/browser.js:4676:15
``

**Comment by Betsy25** [comment]
![Screenshot](http://i.imgur.com/dFn0hMJ.png)

**Comment by Betsy25** [comment]
@sarahavilov Doh! Please forget about my piece of the problem, somehow in about:config, `extensions.secureLogin@blueimp.net.hideToolbarButton` got set to `true` :baby:

**Comment by jxerome** [comment]
The XPI works: the icon is correctly displayed.
Thank you.

**Comment by jxerome** [comment]
Everythinks works correctly nowadays.
