### ISSUE TITLE
Error on Pale Moon 27

### ISSUE THREAD

**Issue by beerisgood** [sarahavilov/secure-login#12]
With Pale Moon 27 x64 (current 27.0.0 alpa2) i get this error in error console:
Error: ReferenceError: qfnServices is not defined
Source File: chrome://securelogin/content/secureLogin.js
Line: 143

Maybe it can be easy fixed?

Link for Pale Moon 27 alpa: http://www.palemoon.org/WIP/

**Comment by sarahavilov** [comment]
Thanks for the report. I pushed a new release which should fix this. Let me know if you sill get this error after the update.

**Comment by beerisgood** [comment]
Thanks you very much for the fast update!
The error is gone.

Nice work!
