### ISSUE TITLE
Secure login toolbar button doesn't work with e10s

### ISSUE THREAD

**Issue by ardisru** [sarahavilov/secure-login#13]
With e10s enabled secure login toolbar button doesn't work. It doesn't do anything on left click, also its tooltip is empty. Right click shows context menu as intended.

Firefox 48.0.2 x64 Windows 10
Secure Login 1.2.3

**Comment by ardisru** [comment]
I've found the workaround. Just enable automatic search of password fields in addon settings (first checkbox)

It works... but with some delay :(

Hope that author can fix SecureLogin or at least fix Log Me In issues with password field search.

**Comment by sarahavilov** [comment]
There will be a WebExtension replacement soon;
https://addons.mozilla.org/en-US/firefox/addon/secure-login-webextension/

For now you can install it in the debug mode and report bugs.
