### ISSUE TITLE
Skip Sites

### ISSUE THREAD

**Issue by MartinN4** [sarahavilov/secure-login#14]
Hello,
is it possible to add a feature, where I can have a list of sites, where I do not want to be asked for a password?
Also I would like to ask whether it is possible to be asked for the master password only once a session and if I do not fill in this masterpassword it should not ask again in that session.
Thanks a lot.
Best regards

**Comment by sarahavilov** [comment]
> is it possible to add a feature, where I can have a list of sites, where I do not want to be asked for a password?

Secure Login (WebExtension) does not ask for passwords, it just displays a badge number and when the toolbar button is hit, it will auto-login you.

> Also I would like to ask whether it is possible to be asked for the master password only once a session and if I do not fill in this masterpassword it should not ask again in that session.

That's exactly how it works right now on the latest release. Update your WebExtension version.
