### ISSUE TITLE
Web Extensions version: Keyboard Shortcut

### ISSUE THREAD

**Issue by acicovic** [sarahavilov/secure-login#16]
Hi Sarah,

First of all thank you for all the work you've put in this add-on.

For the web extensions version, you mention in your page that the keyboard shortcut is "Ctrl+Shift+N". However, this is the default shortcut in Firefox to open a new window, so it doesn't work (a new Firefox window is opened instead).

**Comment by sarahavilov** [comment]
It is Ctrl+Shift+U; http://firefox.add0n.com/secure-login.html#comment-3175589215

I fixed the AMO page. Thanks for the report.

**Comment by acicovic** [comment]
Thanks!
