### ISSUE TITLE
WebExtension version won't submit password only forms

### ISSUE THREAD

**Issue by tomhughes** [sarahavilov/secure-login#18]
Where a form has only a password and the username recorded in the password manager is blank the old version was still happy to fill in the form and submit it when I pressed the button but the WebExtension does not, although it does show a password as available in the counter.

I can right click in the field and select the "No username (date)" entry and then submit manually though.

**Comment by sarahavilov** [comment]
Can you provide an example website with this issue?

**Comment by tomhughes** [comment]
Well the one I am hitting is basically any mailman mailing list where the admin interface only wants a password (for example https://lists.compton.nu/mailman/admindb/oslib-user) but you won't be able to create an account there.

If that's not enough then let me know and I'll create a list that you can be admin on to test it.

**Comment by sarahavilov** [comment]
Thanks for the report. It is fixed on in the dev version. Please give it a try and let me know if the issue is still producible

1. Download https://github.com/sarahavilov/secure-login/blob/master/slogin.xpi?raw=true
2. Open about:debugging
3. Press Load Temporary add-on and point it to the downloaded XPI.

**Comment by tomhughes** [comment]
Yes that does indeed seem to fix it. Thanks.

**Comment by sarahavilov** [comment]
Great!

**Comment by hetmaulik** [comment]
Download https://github.com/sarahavilov/secure-login/blob/master/slogin.xpi?raw=true is broken. will you post the correct one.
