### ISSUE TITLE
login.aliexpress.com is not detected

### ISSUE THREAD

**Issue by crssi** [sarahavilov/secure-login#19]
Classic Secure Login works OK, but this one doesn't detect login

**Comment by sarahavilov** [comment]
WebExtension version matches URL but XUL matches domain name. Matching URL is the right way (this is what is recommended by Firefox and is faster). You just need to modify your login and correct its URL to "https://login.aliexpress.com". Read http://firefox.add0n.com/secure-login.html#comment-3174267555 for more info.
