### ISSUE TITLE
missing shortcut to logins

### ISSUE THREAD

**Issue by crssi** [sarahavilov/secure-login#21]
classic Secure Login has and option to open logins window.
I am missing this feature here.

**Comment by sarahavilov** [comment]
The WebExtension can do that too, however not on the current release of Firefox. Either use the Developer version or wait for the next release of Firefox

See screenshot here;
https://addons.mozilla.org/en-US/firefox/addon/secure-login-webextension/

The code is already in the add-on. Current version of Firefox ignores it!

**Comment by sarahavilov** [comment]
> missing shortcut to logins

The default one is `CTRL+SHIFT+U`. Currently Firefox offers no way to change this default one. I hope this option is added to Firefox soon!

**Comment by crssi** [comment]
Thank you for all your answers... also for other issues.
Great work
