### ISSUE TITLE
add setting to supress Secure Login pop up info

### ISSUE THREAD

**Issue by crssi** [sarahavilov/secure-login#22]
Is it possible to add a setting to suppress pop-up info window, like the one "No matched credential is detected..."
The icon is showing number of logins anyway and pop-up is just a clutter. ;)

Thank you

**Comment by sarahavilov** [comment]
Sure we can have an option to mute the desktop notifications, though when user actually clicks the toolbar while there is no badge number, this notification is going to be shown just to confirm extension actually does something!

We will have this option on the next release.
