### ISSUE TITLE
Patreon Form Not Recognized

### ISSUE THREAD

**Issue by GNIR33NIGN3** [sarahavilov/secure-login#23]
Any workaround for Patreon form?

https://www.patreon.com/login

Thanks.

**Comment by sarahavilov** [comment]
I just checked the WebExtension version and it works just fine on this site

**Comment by GNIR33NIGN3** [comment]
Odd. It does appear to be working now, all of a sudden. Before, it would never prompt me to remember credentials. I suppose that would be the case if browsing anonymously/privately? 

Although, once credentials are saved, it only seems to accept them if I manually click the submit button on the form (in lieu of clicking on the padlock icon in the upper-right corner of the FF browser). Not sure why that is the case.

Nonetheless, thank you for taking the time to reply. This issue is resolved.
