### ISSUE TITLE
Keyboard Shortcuts Support for WebExtensions

### ISSUE THREAD

**Issue by heubergen** [sarahavilov/secure-login#25]
The new Web. API seems to support Keyboard Shortcuts now (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands).
Would be great to add this :)

**Comment by sarahavilov** [comment]
That's exactly we already have;
```js
  "commands": {
    "activate": {
      "suggested_key": {
        "default": "Ctrl+Shift+U"
      },
      "description": "Activate extension"
    }
  },
```
The only issue is it is not yet customizable in Firefox
