### ISSUE TITLE
`dom.event.clipboardevents.enabled` preference dependency

### ISSUE THREAD

**Issue by crssi** [sarahavilov/secure-login#30]
If the preferences `dom.event.clipboardevents.enabled` is set to FALSE, the generate password doesn't copy it to clipboard. It is somehow logic, but is there anyway to overcome this?

cheers

**Comment by sarahavilov** [comment]
Unfortunetly WebExtension does not allow any low level API access and hence when `dom.event.clipboardevents.enabled` is set to false, there would be no way to copy passwords!

**Comment by crssi** [comment]
Understood. Thank you. I have suspect it.
