### ISSUE TITLE
No context menu (with right mouse click) on Windows with FF ESR

### ISSUE THREAD

**Issue by sokai** [sarahavilov/secure-login#36]
Hi!

Since a long time I'm missing the (mouse) right click context menu ("Saved passwords", "Generate a random password", "Help") on the icon in the toolbar/icon bar.
I'm using your WebExtension v0.1.8  on Ubuntu with FF 54, but with Windows 7 and FF ESR (52.2.0) the context menu is not shown.

Do you have some hints? – Or is it a (known) bug?

Thanks in advance and best regards!

**Comment by sarahavilov** [comment]
as far as I remember, context menu for browserAction is introduced in FF 53 or even 54. So you might wait for the next ESR release or switch to the latest non ESR release.
