### ISSUE TITLE
Secure Login (WebExtension) removes character from password

### ISSUE THREAD

**Issue by d4k0** [sarahavilov/secure-login#39]
It seems that "Secure Login (Embedded WebExtension)" removes the character

`

from the password when it inserts it. I noticed this bug when I couldn't login on some sites and Firefox asked me if I want to update the login credentials. After comparing the "new" password with the saved one it turned out that the character " ` " was somehow removed.

I hope this can be fixed.

**Comment by sarahavilov** [comment]
Thanks for the report. It is now fixed on the dev version; https://github.com/sarahavilov/secure-login/blob/master/slogin.xpi?raw=true

**Comment by d4k0** [comment]
Many thanks!
