### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by mautematico** [sarahavilov/secure-login#5]
¡Hola!

I would like to help you with Spanish translation for this addon. Where do I start? Should I directly copy and override English files, or are you using an external system to manage translations (like Pootle, Transifex, etcetera)?

¡Gracias!

**Comment by sarahavilov** [comment]
Hi there, no currently there is no external system to manage translations (there was, but there is no access to it anymore). If you are willing to take care of the translations, you can start a new project on https://www.babelzilla.org/ If not please submit a pull request with sp locales.

**Comment by mautematico** [comment]
Closing this issue, as PR has been merged.
