### ISSUE TITLE
Secure Login do not work with new docker hub login page

### ISSUE THREAD

**Issue by jxerome** [sarahavilov/secure-login#7]
Hello,

Secure login doesn't work with new docker hub login page : https://hub.docker.com/login/
I think some other sites have the same issue.

The page seem to use react and give empty name attributes to the input field.
They provide, however, placeholder attributes.

The classical Firefox way to fill the fields (start typing in name and select it on the completion pop-in) works perfectly so you should be able to deal with these too.

**Comment by sarahavilov** [comment]
Have you tried the WebExtension version yet?

**Comment by jxerome** [comment]
The WebExtension does not work either. Fields remains blank and login is refused.

**Comment by sarahavilov** [comment]
Thanks for the report. This should have been fixed on the dev version now. Please give it a try and let me know if it still has issues

1. Download https://github.com/sarahavilov/secure-login/blob/master/slogin.xpi?raw=true
2. Open about:debugging
3. Press Load Temporary add-on and point it to the downloaded XPI.
