### ISSUE TITLE
Firefox 45.0b4 freezes on login with secure-login

### ISSUE THREAD

**Issue by danbruegge** [sarahavilov/secure-login#8]
Hi,
i'm on Archlinux with Firefox 45.0b4.

I'm using the ALT+N key combination to login.

Only Firefox freezes, nothing else.

**Comment by mautematico** [comment]
Hello @danbruegge 

are you able to provide detailed info?
I think it is needed at least the URL and form (may be an screenshot) where issue is happening, so the developer can take a closer look.

The best!

**Comment by mautematico** [comment]
Also, are you able to try and report back if this is also an issue on Aurora and Nightly?

https://nightly.mozilla.org/
https://aurora.mozilla.org/

**Comment by danbruegge** [comment]
It happens on all pages. No specific url. For example facebook.com.

I looked on my 2 notebooks at home with the same Firefox version. Seems it only appears on the work machine. Tomorrow is will have a closer look on the work machine. Maybe only the ff profile is broken.

**Comment by sarahavilov** [comment]
@danbruegge if you are on an e10s version of Firefox, it is not recommended to use SL, instead try my the other login manager; https://addons.mozilla.org/en-US/firefox/addon/log-me-in/

LogMeIn is much lighter than SL and SL is still not fully e10s compatible.

**Comment by danbruegge** [comment]
Ok, looks like i'm on e10s.
![ff-e10s](https://cloud.githubusercontent.com/assets/1296438/13004054/578e552e-d179-11e5-9d05-d02d04b4811c.png)

I tried LogMeIn and there was no freeze. But where is the Hotkey? Thats the reason why i use SL. :P

**Comment by sarahavilov** [comment]
Log Me In also supports hotkey login. Go to options and change the existing combination.

**Comment by danbruegge** [comment]
Nice, didn't saw this setting. :)
