### ISSUE TITLE
cant enter for a new site new name and password - missing the button at the bottom

### ISSUE THREAD

**Issue by gooly** [sarahavilov/secure-login#9]
Hi,
today I (Win 7-64, FF 45.0.0, and the most recent update of SecureLogin realized that I can't add new sites. At the bottom I used to have a button with a menu behind it so that SecureLogin fetches the name and pwd directly from the page.
Now I have only buttons for "Delete", "Delete All"        "Import", "Show Password".
What happened?
How can I add a new entry?

**Comment by gooly** [comment]
![Uploading p1.PNG…]()
This is how it looks - how can I enter e new entry for TeamWox?

**Comment by sarahavilov** [comment]
can you try re-attaching the screenshot.
